/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Dyn_FL_sub_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[51] = {7, 7, 0, 7, 14, 21, 26, 31, 36, 41, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 5, 6, 0, 1, 2, 5, 6};
static const casadi_int casadi_s3[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};

/* Dyn_FL_sub:(i0[14],i1[4])->(o0[7x7,41nz],o1[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a7, a8, a9;
  a0=arg[0]? arg[0][2] : 0;
  a1=cos(a0);
  a2=5.4600000000000000e+000;
  a3=arg[0]? arg[0][5] : 0;
  a4=cos(a3);
  a5=1.2680000000000000e+000;
  a6=1.2800000000000000e-001;
  a7=arg[0]? arg[0][6] : 0;
  a8=cos(a7);
  a9=(a6*a8);
  a10=(a9*a8);
  a7=sin(a7);
  a11=(a6*a7);
  a12=(a11*a7);
  a10=(a10+a12);
  a10=(a5+a10);
  a12=(a4*a10);
  a3=sin(a3);
  a13=(a6*a8);
  a14=(a13*a7);
  a15=(a6*a7);
  a16=(a15*a8);
  a14=(a14-a16);
  a16=(a3*a14);
  a12=(a12+a16);
  a16=(a12*a4);
  a17=(a11*a8);
  a18=(a9*a7);
  a17=(a17-a18);
  a18=(a4*a17);
  a19=(a15*a7);
  a20=(a13*a8);
  a19=(a19+a20);
  a19=(a5+a19);
  a20=(a3*a19);
  a18=(a18+a20);
  a20=(a18*a3);
  a16=(a16+a20);
  a16=(a2+a16);
  a20=arg[0]? arg[0][3] : 0;
  a21=cos(a20);
  a22=arg[0]? arg[0][4] : 0;
  a23=cos(a22);
  a24=(a6*a23);
  a25=(a24*a23);
  a22=sin(a22);
  a26=(a6*a22);
  a27=(a26*a22);
  a25=(a25+a27);
  a25=(a5+a25);
  a27=(a21*a25);
  a20=sin(a20);
  a28=(a6*a23);
  a29=(a28*a22);
  a30=(a6*a22);
  a31=(a30*a23);
  a29=(a29-a31);
  a31=(a20*a29);
  a27=(a27+a31);
  a31=(a27*a21);
  a32=(a26*a23);
  a33=(a24*a22);
  a32=(a32-a33);
  a33=(a21*a32);
  a34=(a30*a22);
  a35=(a28*a23);
  a34=(a34+a35);
  a34=(a5+a34);
  a35=(a20*a34);
  a33=(a33+a35);
  a35=(a33*a20);
  a31=(a31+a35);
  a16=(a16+a31);
  a31=(a1*a16);
  a0=sin(a0);
  a35=(a4*a14);
  a36=(a3*a10);
  a35=(a35-a36);
  a36=(a35*a4);
  a37=(a4*a19);
  a38=(a3*a17);
  a37=(a37-a38);
  a38=(a37*a3);
  a36=(a36+a38);
  a38=(a21*a29);
  a39=(a20*a25);
  a38=(a38-a39);
  a39=(a38*a21);
  a40=(a21*a34);
  a41=(a20*a32);
  a40=(a40-a41);
  a41=(a40*a20);
  a39=(a39+a41);
  a36=(a36+a39);
  a39=(a0*a36);
  a31=(a31+a39);
  a39=(a31*a1);
  a41=(a18*a4);
  a42=(a12*a3);
  a41=(a41-a42);
  a42=(a33*a21);
  a43=(a27*a20);
  a42=(a42-a43);
  a41=(a41+a42);
  a42=(a1*a41);
  a43=(a37*a4);
  a44=(a35*a3);
  a43=(a43-a44);
  a43=(a2+a43);
  a44=(a40*a21);
  a45=(a38*a20);
  a44=(a44-a45);
  a43=(a43+a44);
  a44=(a0*a43);
  a42=(a42+a44);
  a44=(a42*a0);
  a39=(a39+a44);
  if (res[0]!=0) res[0][0]=a39;
  a42=(a42*a1);
  a31=(a31*a0);
  a42=(a42-a31);
  if (res[0]!=0) res[0][1]=a42;
  a31=-2.5360000000000001e-002;
  a39=-7.8079999999999998e-003;
  a44=(a39*a8);
  a45=-2.0899999999999999e-001;
  a46=(a45*a8);
  a9=(a9*a46);
  a44=(a44+a9);
  a9=(a45*a7);
  a11=(a11*a9);
  a44=(a44+a11);
  a44=(a31+a44);
  a11=(a4*a44);
  a13=(a13*a9);
  a47=(a39*a7);
  a15=(a15*a46);
  a47=(a47+a15);
  a13=(a13-a47);
  a47=(a3*a13);
  a11=(a11+a47);
  a47=1.9000000000000000e-001;
  a15=(a47*a3);
  a12=(a12*a15);
  a11=(a11-a12);
  a47=(a47*a4);
  a18=(a18*a47);
  a11=(a11+a18);
  a18=(a39*a23);
  a12=(a45*a23);
  a24=(a24*a12);
  a18=(a18+a24);
  a45=(a45*a22);
  a26=(a26*a45);
  a18=(a18+a26);
  a18=(a31+a18);
  a26=(a21*a18);
  a28=(a28*a45);
  a24=(a39*a22);
  a30=(a30*a12);
  a24=(a24+a30);
  a28=(a28-a24);
  a24=(a20*a28);
  a26=(a26+a24);
  a24=-1.9000000000000000e-001;
  a30=(a24*a20);
  a27=(a27*a30);
  a26=(a26-a27);
  a24=(a24*a21);
  a33=(a33*a24);
  a26=(a26+a33);
  a11=(a11+a26);
  a26=(a1*a11);
  a33=(a4*a13);
  a27=(a3*a44);
  a33=(a33-a27);
  a35=(a35*a15);
  a33=(a33-a35);
  a37=(a37*a47);
  a33=(a33+a37);
  a37=(a21*a28);
  a35=(a20*a18);
  a37=(a37-a35);
  a38=(a38*a30);
  a37=(a37-a38);
  a40=(a40*a24);
  a37=(a37+a40);
  a33=(a33+a37);
  a37=(a0*a33);
  a26=(a26+a37);
  if (res[0]!=0) res[0][2]=a26;
  a37=(a21*a18);
  a40=(a20*a28);
  a37=(a37+a40);
  a40=(a1*a37);
  a38=(a21*a28);
  a35=(a20*a18);
  a38=(a38-a35);
  a35=(a0*a38);
  a40=(a40+a35);
  if (res[0]!=0) res[0][3]=a40;
  a35=(a39*a23);
  a27=(a21*a35);
  a48=(a39*a22);
  a49=(a20*a48);
  a27=(a27-a49);
  a49=(a1*a27);
  a50=(a20*a35);
  a51=(a21*a48);
  a50=(a50+a51);
  a51=(a0*a50);
  a49=(a49-a51);
  if (res[0]!=0) res[0][4]=a49;
  a51=(a4*a44);
  a52=(a3*a13);
  a51=(a51+a52);
  a52=(a1*a51);
  a53=(a4*a13);
  a54=(a3*a44);
  a53=(a53-a54);
  a54=(a0*a53);
  a52=(a52+a54);
  if (res[0]!=0) res[0][5]=a52;
  a54=(a39*a8);
  a55=(a4*a54);
  a56=(a39*a7);
  a57=(a3*a56);
  a55=(a55-a57);
  a57=(a1*a55);
  a58=(a3*a54);
  a59=(a4*a56);
  a58=(a58+a59);
  a59=(a0*a58);
  a57=(a57-a59);
  if (res[0]!=0) res[0][6]=a57;
  if (res[0]!=0) res[0][7]=a42;
  a43=(a1*a43);
  a41=(a0*a41);
  a43=(a43-a41);
  a43=(a43*a1);
  a36=(a1*a36);
  a16=(a0*a16);
  a36=(a36-a16);
  a36=(a36*a0);
  a43=(a43-a36);
  if (res[0]!=0) res[0][8]=a43;
  a33=(a1*a33);
  a11=(a0*a11);
  a33=(a33-a11);
  if (res[0]!=0) res[0][9]=a33;
  a38=(a1*a38);
  a37=(a0*a37);
  a38=(a38-a37);
  if (res[0]!=0) res[0][10]=a38;
  a27=(a0*a27);
  a50=(a1*a50);
  a27=(a27+a50);
  a27=(-a27);
  if (res[0]!=0) res[0][11]=a27;
  a53=(a1*a53);
  a51=(a0*a51);
  a53=(a53-a51);
  if (res[0]!=0) res[0][12]=a53;
  a55=(a0*a55);
  a58=(a1*a58);
  a55=(a55+a58);
  a55=(-a55);
  if (res[0]!=0) res[0][13]=a55;
  if (res[0]!=0) res[0][14]=a26;
  if (res[0]!=0) res[0][15]=a33;
  a33=1.1641900000000001e-001;
  a26=4.7131999999999999e-003;
  a58=9.7228799999999997e-004;
  a51=(a39*a46);
  a51=(a58+a51);
  a50=(a6*a46);
  a50=(a39+a50);
  a37=(a50*a46);
  a51=(a51+a37);
  a37=(a6*a9);
  a11=(a37*a9);
  a51=(a51+a11);
  a51=(a26+a51);
  a11=(a15*a44);
  a11=(a51-a11);
  a43=(a47*a13);
  a11=(a11+a43);
  a43=(a50*a8);
  a36=(a37*a7);
  a43=(a43+a36);
  a43=(a31+a43);
  a10=(a15*a10);
  a43=(a43-a10);
  a14=(a47*a14);
  a43=(a43+a14);
  a43=(a43*a15);
  a11=(a11-a43);
  a37=(a37*a8);
  a50=(a50*a7);
  a37=(a37-a50);
  a17=(a15*a17);
  a37=(a37-a17);
  a19=(a47*a19);
  a37=(a37+a19);
  a37=(a37*a47);
  a11=(a11+a37);
  a33=(a33+a11);
  a11=(a39*a12);
  a11=(a58+a11);
  a37=(a6*a12);
  a37=(a39+a37);
  a19=(a37*a12);
  a11=(a11+a19);
  a19=(a6*a45);
  a17=(a19*a45);
  a11=(a11+a17);
  a26=(a26+a11);
  a11=(a30*a18);
  a11=(a26-a11);
  a17=(a24*a28);
  a11=(a11+a17);
  a17=(a37*a23);
  a50=(a19*a22);
  a17=(a17+a50);
  a17=(a31+a17);
  a25=(a30*a25);
  a17=(a17-a25);
  a29=(a24*a29);
  a17=(a17+a29);
  a17=(a17*a30);
  a11=(a11-a17);
  a19=(a19*a23);
  a37=(a37*a22);
  a19=(a19-a37);
  a32=(a30*a32);
  a19=(a19-a32);
  a34=(a24*a34);
  a19=(a19+a34);
  a19=(a19*a24);
  a11=(a11+a19);
  a33=(a33+a11);
  if (res[0]!=0) res[0][16]=a33;
  a18=(a30*a18);
  a18=(a26-a18);
  a28=(a24*a28);
  a18=(a18+a28);
  if (res[0]!=0) res[0][17]=a18;
  a28=(a39*a12);
  a28=(a58+a28);
  a35=(a30*a35);
  a35=(a28-a35);
  a48=(a24*a48);
  a35=(a35-a48);
  if (res[0]!=0) res[0][18]=a35;
  a44=(a15*a44);
  a44=(a51-a44);
  a13=(a47*a13);
  a44=(a44+a13);
  if (res[0]!=0) res[0][19]=a44;
  a13=(a39*a46);
  a13=(a58+a13);
  a54=(a15*a54);
  a54=(a13-a54);
  a56=(a47*a56);
  a54=(a54-a56);
  if (res[0]!=0) res[0][20]=a54;
  if (res[0]!=0) res[0][21]=a40;
  if (res[0]!=0) res[0][22]=a38;
  if (res[0]!=0) res[0][23]=a18;
  if (res[0]!=0) res[0][24]=a26;
  if (res[0]!=0) res[0][25]=a28;
  if (res[0]!=0) res[0][26]=a49;
  if (res[0]!=0) res[0][27]=a27;
  if (res[0]!=0) res[0][28]=a35;
  if (res[0]!=0) res[0][29]=a28;
  if (res[0]!=0) res[0][30]=a58;
  if (res[0]!=0) res[0][31]=a52;
  if (res[0]!=0) res[0][32]=a53;
  if (res[0]!=0) res[0][33]=a44;
  if (res[0]!=0) res[0][34]=a51;
  if (res[0]!=0) res[0][35]=a13;
  if (res[0]!=0) res[0][36]=a57;
  if (res[0]!=0) res[0][37]=a55;
  if (res[0]!=0) res[0][38]=a54;
  if (res[0]!=0) res[0][39]=a13;
  if (res[0]!=0) res[0][40]=a58;
  a58=arg[0]? arg[0][9] : 0;
  a13=(a2*a58);
  a54=arg[0]? arg[0][7] : 0;
  a55=(a0*a54);
  a57=arg[0]? arg[0][8] : 0;
  a51=(a1*a57);
  a55=(a55+a51);
  a13=(a13*a55);
  a51=9.8100000000000005e+000;
  a44=(a51*a0);
  a53=(a55*a58);
  a44=(a44+a53);
  a53=(a2*a44);
  a13=(a13-a53);
  a53=arg[0]? arg[0][12] : 0;
  a52=(a58+a53);
  a28=(a5*a52);
  a35=(a47*a58);
  a54=(a1*a54);
  a57=(a0*a57);
  a54=(a54-a57);
  a57=(a3*a54);
  a35=(a35+a57);
  a57=(a4*a55);
  a35=(a35+a57);
  a28=(a28*a35);
  a57=(a4*a44);
  a51=(a51*a1);
  a27=(a54*a58);
  a51=(a51+a27);
  a27=(a3*a51);
  a57=(a57+a27);
  a27=(a35*a53);
  a57=(a57+a27);
  a27=(a5*a57);
  a28=(a28-a27);
  a27=arg[0]? arg[0][13] : 0;
  a49=(a52+a27);
  a26=(a6*a49);
  a18=(a9*a52);
  a38=(a4*a54);
  a40=(a15*a58);
  a38=(a38-a40);
  a40=(a3*a55);
  a38=(a38-a40);
  a40=(a7*a38);
  a18=(a18+a40);
  a40=(a8*a35);
  a18=(a18+a40);
  a26=(a26*a18);
  a40=(a8*a57);
  a56=(a4*a51);
  a48=(a3*a44);
  a56=(a56-a48);
  a53=(a38*a53);
  a56=(a56+a53);
  a53=(a7*a56);
  a40=(a40+a53);
  a53=(a18*a27);
  a40=(a40+a53);
  a53=(a6*a40);
  a26=(a26-a53);
  a53=(a8*a26);
  a48=(a8*a56);
  a33=(a7*a57);
  a48=(a48-a33);
  a33=(a46*a52);
  a11=(a8*a38);
  a33=(a33+a11);
  a11=(a7*a35);
  a33=(a33-a11);
  a27=(a33*a27);
  a48=(a48+a27);
  a48=(a6*a48);
  a27=(a39*a49);
  a27=(a27*a49);
  a11=(a6*a49);
  a11=(a11*a33);
  a27=(a27+a11);
  a48=(a48-a27);
  a27=(a7*a48);
  a53=(a53+a27);
  a28=(a28+a53);
  a53=(a4*a28);
  a56=(a5*a56);
  a27=(a31*a52);
  a27=(a27*a52);
  a11=(a5*a52);
  a11=(a11*a38);
  a27=(a27+a11);
  a56=(a56-a27);
  a8=(a8*a48);
  a7=(a7*a26);
  a8=(a8-a7);
  a56=(a56+a8);
  a8=(a3*a56);
  a53=(a53+a8);
  a13=(a13+a53);
  a53=arg[0]? arg[0][10] : 0;
  a8=(a58+a53);
  a7=(a5*a8);
  a27=(a24*a58);
  a11=(a20*a54);
  a27=(a27+a11);
  a11=(a21*a55);
  a27=(a27+a11);
  a7=(a7*a27);
  a11=(a21*a44);
  a19=(a20*a51);
  a11=(a11+a19);
  a19=(a27*a53);
  a11=(a11+a19);
  a19=(a5*a11);
  a7=(a7-a19);
  a19=arg[0]? arg[0][11] : 0;
  a34=(a8+a19);
  a32=(a6*a34);
  a37=(a45*a8);
  a17=(a21*a54);
  a29=(a30*a58);
  a17=(a17-a29);
  a29=(a20*a55);
  a17=(a17-a29);
  a29=(a22*a17);
  a37=(a37+a29);
  a29=(a23*a27);
  a37=(a37+a29);
  a32=(a32*a37);
  a29=(a23*a11);
  a25=(a21*a51);
  a44=(a20*a44);
  a25=(a25-a44);
  a53=(a17*a53);
  a25=(a25+a53);
  a53=(a22*a25);
  a29=(a29+a53);
  a53=(a37*a19);
  a29=(a29+a53);
  a53=(a6*a29);
  a32=(a32-a53);
  a53=(a23*a32);
  a44=(a23*a25);
  a50=(a22*a11);
  a44=(a44-a50);
  a50=(a12*a8);
  a43=(a23*a17);
  a50=(a50+a43);
  a43=(a22*a27);
  a50=(a50-a43);
  a19=(a50*a19);
  a44=(a44+a19);
  a44=(a6*a44);
  a19=(a39*a34);
  a19=(a19*a34);
  a43=(a6*a34);
  a43=(a43*a50);
  a19=(a19+a43);
  a44=(a44-a19);
  a19=(a22*a44);
  a53=(a53+a19);
  a7=(a7+a53);
  a53=(a21*a7);
  a25=(a5*a25);
  a19=(a31*a8);
  a19=(a19*a8);
  a43=(a5*a8);
  a43=(a43*a17);
  a19=(a19+a43);
  a25=(a25-a19);
  a23=(a23*a44);
  a22=(a22*a32);
  a23=(a23-a22);
  a25=(a25+a23);
  a23=(a20*a25);
  a53=(a53+a23);
  a13=(a13+a53);
  a53=(a1*a13);
  a51=(a2*a51);
  a58=(a2*a58);
  a58=(a58*a54);
  a51=(a51-a58);
  a4=(a4*a56);
  a3=(a3*a28);
  a4=(a4-a3);
  a51=(a51+a4);
  a21=(a21*a25);
  a20=(a20*a7);
  a21=(a21-a20);
  a51=(a51+a21);
  a21=(a0*a51);
  a53=(a53+a21);
  a53=(-a53);
  if (res[1]!=0) res[1][0]=a53;
  a1=(a1*a51);
  a0=(a0*a13);
  a1=(a1-a0);
  a1=(-a1);
  if (res[1]!=0) res[1][1]=a1;
  a1=(a2*a55);
  a1=(a1*a54);
  a2=(a2*a54);
  a2=(a2*a55);
  a1=(a1-a2);
  a2=(a31*a35);
  a2=(a2*a52);
  a52=(a5*a35);
  a52=(a52*a38);
  a2=(a2+a52);
  a38=(a5*a38);
  a38=(a38*a35);
  a2=(a2-a38);
  a57=(a31*a57);
  a2=(a2-a57);
  a57=(a39*a18);
  a57=(a57*a49);
  a49=(a6*a18);
  a49=(a49*a33);
  a57=(a57+a49);
  a33=(a6*a33);
  a33=(a33*a18);
  a57=(a57-a33);
  a40=(a39*a40);
  a57=(a57-a40);
  a46=(a46*a26);
  a46=(a57+a46);
  a9=(a9*a48);
  a46=(a46+a9);
  a2=(a2+a46);
  a15=(a15*a28);
  a15=(a2-a15);
  a47=(a47*a56);
  a15=(a15+a47);
  a1=(a1+a15);
  a15=(a31*a27);
  a15=(a15*a8);
  a8=(a5*a27);
  a8=(a8*a17);
  a15=(a15+a8);
  a5=(a5*a17);
  a5=(a5*a27);
  a15=(a15-a5);
  a31=(a31*a11);
  a15=(a15-a31);
  a31=(a39*a37);
  a31=(a31*a34);
  a34=(a6*a37);
  a34=(a34*a50);
  a31=(a31+a34);
  a6=(a6*a50);
  a6=(a6*a37);
  a31=(a31-a6);
  a39=(a39*a29);
  a31=(a31-a39);
  a12=(a12*a32);
  a12=(a31+a12);
  a45=(a45*a44);
  a12=(a12+a45);
  a15=(a15+a12);
  a30=(a30*a7);
  a30=(a15-a30);
  a24=(a24*a25);
  a30=(a30+a24);
  a1=(a1+a30);
  a1=(-a1);
  if (res[1]!=0) res[1][2]=a1;
  a1=arg[1]? arg[1][0] : 0;
  a1=(a1-a15);
  if (res[1]!=0) res[1][3]=a1;
  a1=arg[1]? arg[1][1] : 0;
  a1=(a1-a31);
  if (res[1]!=0) res[1][4]=a1;
  a1=arg[1]? arg[1][2] : 0;
  a1=(a1-a2);
  if (res[1]!=0) res[1][5]=a1;
  a1=arg[1]? arg[1][3] : 0;
  a1=(a1-a57);
  if (res[1]!=0) res[1][6]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int Dyn_FL_sub(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Dyn_FL_sub_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Dyn_FL_sub_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dyn_FL_sub_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Dyn_FL_sub_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dyn_FL_sub_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Dyn_FL_sub_incref(void) {
}

CASADI_SYMBOL_EXPORT void Dyn_FL_sub_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Dyn_FL_sub_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int Dyn_FL_sub_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Dyn_FL_sub_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dyn_FL_sub_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dyn_FL_sub_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dyn_FL_sub_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dyn_FL_sub_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Dyn_FL_sub_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
